// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Credential struct {
	ID     []byte
	UserID []byte
	Data   []byte
}

type LoginAttempt struct {
	TokenHash []byte
	Ceremony  []byte
	ExpiresAt pgtype.Timestamptz
}

type RegistrationAttempt struct {
	TokenHash []byte
	UserID    []byte
	Name      string
	Ceremony  []byte
	ExpiresAt pgtype.Timestamptz
}

type Session struct {
	TokenHash []byte
	UserID    []byte
	ExpiresAt pgtype.Timestamptz
}

type User struct {
	ID        []byte
	Name      string
	CreatedAt pgtype.Timestamptz
}
