// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteLoginAttempt = `-- name: DeleteLoginAttempt :one
DELETE FROM login_attempts
WHERE token_hash = $1 AND expires_at > now()
RETURNING ceremony
`

func (q *Queries) DeleteLoginAttempt(ctx context.Context, tokenHash []byte) ([]byte, error) {
	row := q.db.QueryRow(ctx, deleteLoginAttempt, tokenHash)
	var ceremony []byte
	err := row.Scan(&ceremony)
	return ceremony, err
}

const deleteRegistrationAttempt = `-- name: DeleteRegistrationAttempt :one
DELETE FROM registration_attempts
WHERE token_hash = $1 AND expires_at > now()
RETURNING user_id, name, ceremony
`

type DeleteRegistrationAttemptRow struct {
	UserID   []byte
	Name     string
	Ceremony []byte
}

func (q *Queries) DeleteRegistrationAttempt(ctx context.Context, tokenHash []byte) (DeleteRegistrationAttemptRow, error) {
	row := q.db.QueryRow(ctx, deleteRegistrationAttempt, tokenHash)
	var i DeleteRegistrationAttemptRow
	err := row.Scan(&i.UserID, &i.Name, &i.Ceremony)
	return i, err
}

const getUserByCredential = `-- name: GetUserByCredential :one
SELECT users.id, users.name, credentials.data
FROM credentials
JOIN users ON users.id = credentials.user_id
WHERE credentials.id = $1 AND users.id = $2
`

type GetUserByCredentialParams struct {
	CredentialID []byte
	UserID       []byte
}

type GetUserByCredentialRow struct {
	ID   []byte
	Name string
	Data []byte
}

func (q *Queries) GetUserByCredential(ctx context.Context, arg GetUserByCredentialParams) (GetUserByCredentialRow, error) {
	row := q.db.QueryRow(ctx, getUserByCredential, arg.CredentialID, arg.UserID)
	var i GetUserByCredentialRow
	err := row.Scan(&i.ID, &i.Name, &i.Data)
	return i, err
}

const getUserBySession = `-- name: GetUserBySession :one
SELECT users.id, users.name
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1 AND sessions.expires_at > now()
`

type GetUserBySessionRow struct {
	ID   []byte
	Name string
}

func (q *Queries) GetUserBySession(ctx context.Context, tokenHash []byte) (GetUserBySessionRow, error) {
	row := q.db.QueryRow(ctx, getUserBySession, tokenHash)
	var i GetUserBySessionRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const insertCredential = `-- name: InsertCredential :exec
INSERT INTO credentials (id, user_id, data)
VALUES ($1, $2, $3)
`

type InsertCredentialParams struct {
	ID     []byte
	UserID []byte
	Data   []byte
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) error {
	_, err := q.db.Exec(ctx, insertCredential, arg.ID, arg.UserID, arg.Data)
	return err
}

const insertLoginAttempt = `-- name: InsertLoginAttempt :exec
INSERT INTO login_attempts (token_hash, ceremony, expires_at)
VALUES ($1, $2, $3)
`

type InsertLoginAttemptParams struct {
	TokenHash []byte
	Ceremony  []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertLoginAttempt(ctx context.Context, arg InsertLoginAttemptParams) error {
	_, err := q.db.Exec(ctx, insertLoginAttempt, arg.TokenHash, arg.Ceremony, arg.ExpiresAt)
	return err
}

const insertRegistrationAttempt = `-- name: InsertRegistrationAttempt :exec
INSERT INTO registration_attempts (token_hash, user_id, name, ceremony, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRegistrationAttemptParams struct {
	TokenHash []byte
	UserID    []byte
	Name      string
	Ceremony  []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertRegistrationAttempt(ctx context.Context, arg InsertRegistrationAttemptParams) error {
	_, err := q.db.Exec(ctx, insertRegistrationAttempt,
		arg.TokenHash,
		arg.UserID,
		arg.Name,
		arg.Ceremony,
		arg.ExpiresAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type InsertSessionParams struct {
	TokenHash []byte
	UserID    []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, name)
VALUES ($1, $2)
`

type InsertUserParams struct {
	ID   []byte
	Name string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser, arg.ID, arg.Name)
	return err
}

const updateCredential = `-- name: UpdateCredential :exec
UPDATE credentials SET data = $1
WHERE id = $2 AND user_id = $3
`

type UpdateCredentialParams struct {
	Data   []byte
	ID     []byte
	UserID []byte
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error {
	_, err := q.db.Exec(ctx, updateCredential, arg.Data, arg.ID, arg.UserID)
	return err
}
