[tools]
# Misc.
pulumi = "latest"
"github:MrLesk/Backlog.md" = "latest"
hk = "latest"
pkl = "latest"
# Needed for pkl language server
java = "24"

# Golang
go = "1.26"
gofumpt = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"
"github:golangci/golines" = "latest"
"github:securego/gosec" = "latest"
golangci-lint = "latest"

# Web
node = "24"
pnpm = "11"
oxlint = "latest"

[shell_alias]
backlog = "backlog-bun"

# === Development ===

[tasks.dev]
description = "Run in development mode"
depends = ["dev-fe", "dev-be"]

[tasks.dev-fe]
dir = "frontend"
run = "pnpm dev"
hide = true

[tasks.dev-be]
dir = "backend"
run = "go run ./cmd/laga"
env.EXTERNAL_WEB_SERVER_ADDRESS = "http://localhost:5173"
env.PORT = 8080
hide = true

# === Building ===

[tasks.build]
depends = ["build-fe"]
dir = "backend/cmd/laga"
run = "go build ."
env.CGO_ENABLED = 0
hide = true

[tasks.build-fe]
dir = "frontend"
run = "pnpm run build"
hide = true

[tasks.preview]
description = "Preview build for production"
depends = ["build-fe"]
dir = "backend/cmd/laga"
run = "go run ."
env.PORT = 9090

# === Backlog ===

[tasks.backlog-web]
description = "Run backlog web UI"
run = "backlog-bun browser"
