name: Deploy
description: Deploy application

inputs:
  secret-key:
    description: Scaleway Secret Key
    required: true
  access-key:
    description: Scaleway Access Key
    required: true

runs:
  using: composite
  steps:
    - name: Cache Pulumi plugins
      uses: actions/cache@v5
      with:
        path: ~/.pulumi/plugins
        key: ${{ runner.os }}-pulumi-${{ github.ref_name }}-${{ hashFiles('deploy/infra/go.mod', 'deploy/infra/Pulumi.*.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pulumi-${{ github.ref_name }}-
          ${{ runner.os }}-pulumi-

    - name: Install Go dependencies (deploy)
      working-directory: deploy/infra
      shell: bash
      run: go mod download

    - name: Deploy
      shell: bash
      working-directory: deploy/infra
      env:
        SCW_SECRET_KEY: ${{ inputs.secret-key }}
        AWS_SECRET_KEY: ${{ inputs.secret-key }}
        SCW_ACCESS_KEY: ${{ inputs.access-key }}
        AWS_ACCESS_KEY: ${{ inputs.access-key }}
        PULUMI_CONFIG_PASSPHRASE: ""
      run: |
        pulumi login 's3://laga-pulumi-state?endpoint=https://s3.fr-par.scw.cloud&region=fr-par'
        pulumi stack select prod
        pulumi up --yes --non-interactive --suppress-progress
