encryptionsalt: v1:0JvN04YKAxc=:v1:sQ658t5S8aQ3C/Yr:1UcaTpVvbCml3DC8axZKLPJW2+yvHA==
config:
  laga:databaseApplicationId: a130199a-2844-40d9-badf-29f2e9bf0d72
  laga:databaseSecretKey:
    secure: v1:Db2rjSD6NPkMWmr2:gxtKaiFt8gF4KlSUa3Aptj3zLdxLGCC4HgeLXZZZGvxSdbhLzvs8p4yNpiz6CbK5HPWjAg==
