export type DepartmentId =
  | "produce"
  | "dairy"
  | "meat_seafood"
  | "bakery"
  | "frozen"
  | "pantry"
  | "beverages"
  | "breakfast"
  | "snacks"
  | "personal_care"
  | "household"
  | "baby"
  | "other";

export interface Department {
  id: DepartmentId;
  name: string;
  sortOrder: number;
  keywords: string[];
}

export const departments: Department[] = [
  {
    id: "produce",
    name: "Frukt & grönt",
    sortOrder: 1,
    keywords: [
      "äpple",
      "äpplen",
      "banan",
      "bananer",
      "apelsin",
      "apelsiner",
      "citron",
      "citroner",
      "lime",
      "limes",
      "vindruvor",
      "druvor",
      "jordgubbar",
      "hallon",
      "blåbär",
      "björnbär",
      "lingon",
      "kiwi",
      "kivifrukt",
      "mango",
      "avokado",
      "päron",
      "persika",
      "plommon",
      "nektarin",
      "melon",
      "vattenmelon",
      "ananas",
      "granatäpple",
      "fikon",
      "rabarber",
      "körsbär",
      "potatis",
      "lök",
      "gul lök",
      "röd lök",
      "vitlök",
      "purjolök",
      "morot",
      "morötter",
      "tomat",
      "tomater",
      "körsbärstomat",
      "körsbärstomater",
      "gurka",
      "saltgurka",
      "sallad",
      "isbergssallad",
      "ruccola",
      "spenat",
      "machesallad",
      "broccoli",
      "blomkål",
      "vitkål",
      "rödkål",
      "grönkål",
      "savojkål",
      "paprika",
      "chili",
      "squash",
      "zucchini",
      "aubergine",
      "auberginer",
      "majs",
      "ärter",
      "ärtor",
      "bönor",
      "gröna bönor",
      "haricots verts",
      "sötpotatis",
      "palsternacka",
      "rotselleri",
      "rädisa",
      "fänkål",
      "svamp",
      "champinjoner",
      "skogssvamp",
      "persilja",
      "basilika",
      "mynta",
      "koriander",
      "rosmarin",
      "timjan",
      "dill",
      "gräslök",
      "salvia",
      "oregano",
      "färska örter",
      "salladspåse",
      "färdigskuren sallad",
      "salladsmix",
      "sköljd sallad",
      "babyspenat",
      "sparris",
      "frukt",
    ],
  },
  {
    id: "dairy",
    name: "Mejeri",
    sortOrder: 2,
    keywords: [
      "mjölk",
      "standardmjölk",
      "lättmjölk",
      "mellanmjölk",
      "ekologisk mjölk",
      "filmjölk",
      "fil",
      "yoghurt",
      "naturell yoghurt",
      "grekisk yoghurt",
      "kvarg",
      "keso",
      "kesella",
      "crème fraiche",
      "creme fraiche",
      "gräddfil",
      "grädde",
      "vispgrädde",
      "matlagningsgrädde",
      "kaffegrädde",
      "smör",
      "margarin",
      "bregott",
      "lättmargarin",
      "ost",
      "hårdost",
      "mjukost",
      "färskost",
      "mozzarella",
      "parmesan",
      "cheddar",
      "herrgård",
      "grevé",
      "prästost",
      "feta",
      "fetaost",
      "ädelost",
      "mögelost",
      "brie",
      "camembert",
      "cream cheese",
      "philadelphia",
      "mascarpone",
      "halloumi",
      "ägg",
      "ägg",
      "laktosfri",
      "laktos",
      "havredryck",
      "havremjölk",
      "sojadryck",
      "sojamjölk",
      "mandeldryck",
      "mandelmjölk",
      "oatly",
      "äggkartong",
      "färsk mjölk",
      "hållbar mjölk",
      "burrata",
    ],
  },
  {
    id: "meat_seafood",
    name: "Kött & fisk",
    sortOrder: 3,
    keywords: [
      "kyckling",
      "kycklingfilé",
      "kycklingklubba",
      "kycklingben",
      "kycklinglår",
      "kycklingbröst",
      "kycklingfärs",
      "kycklingkorv",
      "fläsk",
      "fläskfilé",
      "fläskkotlett",
      "fläskkarré",
      "bog",
      "skinka",
      "rökt skinka",
      "julskinka",
      "pålägg",
      "salami",
      "skivad skinka",
      "leverpastej",
      "pastej",
      "korv",
      "falukorv",
      "prinskorv",
      "wienerkorv",
      "bratwurst",
      "chorizo",
      "salsiccia",
      "köttfärs",
      "nötfärs",
      "blandfärs",
      "högrev",
      "entrecote",
      "biff",
      "rostbiff",
      "lövbiff",
      "oxfilé",
      "nötkött",
      "lamm",
      "lammfärs",
      "lammstek",
      "lammkotlett",
      "lax",
      "rökt lax",
      "gravad lax",
      "räkor",
      "torsk",
      "sej",
      "makrill",
      "sill",
      "strömming",
      "tonfisk",
      "krabba",
      "musslor",
      "fiskpinnar",
      "fiskfilé",
      "torskfilé",
      "bacon",
      "revbensspjäll",
      "köttbullar",
      "kassler",
      "chark",
      "charkuteri",
      "kalkon",
      "kalkonfilé",
      "ankfilé",
      "vilt",
      "älg",
      "hjort",
      "vildsvin",
    ],
  },
  {
    id: "bakery",
    name: "Bröd & bageri",
    sortOrder: 4,
    keywords: [
      "bröd",
      "rågbröd",
      "limpa",
      "formfranska",
      "tekaka",
      "rostat bröd",
      "rostbröd",
      "knäckebröd",
      "hårt bröd",
      "mjukt bröd",
      "surdegsbröd",
      "surdeg",
      "fralla",
      "franskbröd",
      "baguette",
      "ciabatta",
      "pita",
      "pita bröd",
      "tunnbröd",
      "tortilla",
      "wrap",
      "libabröd",
      "naan",
      "bulle",
      "kanelbulle",
      "kaka",
      "chokladboll",
      "muffin",
      "scone",
      "croissant",
      "wienerbröd",
      "kringla",
      "småkaka",
      "små kaka",
      "kex",
      "skorpa",
      "skorpor",
      "nygräddat",
      "bageri",
      "bageribröd",
      "färskt bröd",
    ],
  },
  {
    id: "frozen",
    name: "Fryst",
    sortOrder: 5,
    keywords: [
      "glass",
      "vaniljglass",
      "chokladglass",
      "sorbet",
      "glasspuck",
      "pinnglass",
      "strutglass",
      "glassstrut",
      "magnum",
      "fryst",
      "fryst pizza",
      "fryst fisk",
      "fryst kyckling",
      "frysta grönsaker",
      "fryst spenat",
      "fryst broccoli",
      "frysta bär",
      "fryst potatis",
      "fryst pommes frites",
      "pommes",
      "pommes frites",
      "frysta ärtor",
      "ärtor frysta",
      "fryst färdigmat",
      "fryst lasagne",
      "fryst pyttipanna",
      "pyttipanna",
      "fryst soppa",
      "fryst paj",
      "fryst bröd",
      "frysta bullar",
      "fryst våffla",
      "våffla fryst",
      "fryst efterrätt",
      "fryst tårta",
      "fiskpinnar fryst",
      "vegetariskt fryst",
    ],
  },
  {
    id: "pantry",
    name: "Skafferi",
    sortOrder: 6,
    keywords: [
      "pasta",
      "spaghetti",
      "makaroner",
      "penne",
      "fusilli",
      "lasagneplattor",
      "nudlar",
      "risoni",
      "ris",
      "basmatiris",
      "jasminris",
      "arborioris",
      "quinoa",
      "couscous",
      "bulgur",
      "matvete",
      "korn",
      "hirs",
      "havregryn",
      "gryn",
      "gröt",
      "mjöl",
      "vetemjöl",
      "rågmjöl",
      "dinkelmjöl",
      "mandelmjöl",
      "socker",
      "strösocker",
      "florsocker",
      "farinsocker",
      "rårörsocker",
      "vaniljsocker",
      "bakpulver",
      "jäst",
      "torrjäst",
      "bikarbonat",
      "kardemumma",
      "olja",
      "matolja",
      "rapsolja",
      "olivolja",
      "kokosolja",
      "vinäger",
      "ättika",
      "salt",
      "peppar",
      "kryddor",
      "basilika torkad",
      "oregano torkad",
      "timjan torkad",
      "spiskummin",
      "paprika krydda",
      "curry",
      "gurkmeja",
      "chili",
      "kanel",
      "kardemumma",
      "nejlika",
      "lagerblad",
      "konserver",
      "krossade tomater",
      "hela tomater",
      "tomatpuré",
      "bönor konserverade",
      "kikärter",
      "kidneybönor",
      "svarta bönor",
      "majs konserverad",
      "tonfisk på burk",
      "tonfisk i burk",
      "burktonfisk",
      "makrill i tomatsås",
      "sardiner",
      "ansjovis",
      "soppa",
      "buljong",
      "fond",
      "kycklingbuljong",
      "grönsaksbuljong",
      "köttbuljong",
      "buljongtärning",
      "buljongtärningar",
      "soppåse",
      "soppmix",
      "sylt",
      "jordgubbssylt",
      "hallonsylt",
      "marmelad",
      "apelsinmarmelad",
      "honung",
      "nutella",
      "jordnötssmör",
      "ketchup",
      "senap",
      "majonnäs",
      "dressing",
      "soja",
      "soyasås",
      "soya",
      "chilisås",
      "barbecuesås",
      "oliver",
      "kapris",
      "müsli",
      "flingor",
      "cornflakes",
      "havregryn",
      "gröt",
      "kakao",
      "havrefras",
      "havrekuddar",
      "ananas på burk",
      "ananas i burk",
      "burkananas",
      "på burk",
      "i burk",
      "inlagd",
      "tacokrydda",
      "tacoskrydda",
      "tacossås",
      "tortillas",
    ],
  },
  {
    id: "beverages",
    name: "Dryck",
    sortOrder: 7,
    keywords: [
      "kaffe",
      "bryggkaffe",
      "snabbkaffe",
      "espresso",
      "kaffekapslar",
      "kaffefilter",
      "kaffepulver",
      "te",
      "svart te",
      "grönt te",
      "örtte",
      "fruktte",
      "chai",
      "rooibos",
      "juice",
      "apelsinjuice",
      "äppeljuice",
      "tomatjuice",
      "smoothie",
      "saft",
      "koncentrerad saft",
      "vatten",
      "mineralvatten",
      "bubbelvatten",
      "kolsyrat vatten",
      "läsk",
      "cola",
      "sprite",
      "pepsi",
      "sockerdricka",
      "energidryck",
      "energy drink",
      "red bull",
      "öl",
      "ljusöl",
      "mörköl",
      "lager",
      "ale",
      "stout",
      "porter",
      "cider",
      "vin",
      "rött vin",
      "vitt vin",
      "rosévin",
      "mousserande vin",
      "champagne",
      "starkvin",
      "portvin",
      "sprit",
      "vodka",
      "whiskey",
      "whisky",
      "gin",
      "rom",
      "likör",
      "glögg",
      "must",
    ],
  },
  {
    id: "snacks",
    name: "Snacks & godis",
    sortOrder: 8,
    keywords: [
      "godis",
      "lösgodis",
      "godispåse",
      "choklad",
      "mjölkchoklad",
      "mörk choklad",
      "vit choklad",
      "chokladkaka",
      "chokladask",
      "pralin",
      "kexchoklad",
      "klubba",
      "karamell",
      "lakrits",
      "saltlakrits",
      "gelé",
      "skumgodis",
      "marshmallow",
      "chips",
      "potatischips",
      "tortillachips",
      "ostbågar",
      "dip",
      "nachos",
      "popcorn",
      "jordnötter",
      "cashewnötter",
      "mandel",
      "valnötter",
      "hasselnötter",
      "pecannötter",
      "mixnötter",
      "nötter",
      "trail mix",
      "torkad frukt",
      "russin",
      "aprikoser",
      "dadlar",
      "kex",
      "småkakor",
      "kakor",
      "brownie",
      "cookie",
      "cookies",
    ],
  },
  {
    id: "personal_care",
    name: "Hygien & hälsa",
    sortOrder: 9,
    keywords: [
      "schampo",
      "shampoo",
      "balsam",
      "hårtvål",
      "hårvård",
      "tvål",
      "duschtvål",
      "handtvål",
      "ansiktstvål",
      "ansiktstvätt",
      "hudkräm",
      "ansiktskräm",
      "dagkräm",
      "nattkräm",
      "solkräm",
      "solskydd",
      "solspray",
      "deodorant",
      "deo",
      "parfym",
      "rakhyvel",
      "rakblad",
      "raklödder",
      "rakgel",
      "tandborste",
      "tandkräm",
      "munskölj",
      "tandtråd",
      "mascara",
      "ögonskugga",
      "foundation",
      "läppstift",
      "läppbalsam",
      "smink",
      "makeup",
      "vitaminer",
      "kosttillskott",
      "omega-3",
      "multivitamin",
      "c-vitamin",
      "cvitamin",
      "vitamin c",
      "d-vitamin",
      "dvitamin",
      "vitamin d",
      "järn",
      "allergi",
      "hosta",
      "förkylning",
      "huvudvärk",
      "ipren",
      "alvedon",
      "värktablett",
      "värkmedicin",
      "nässprej",
      "näsprej",
      "plåster",
      "bandage",
      "sårvård",
      "febertermometer",
    ],
  },
  {
    id: "household",
    name: "Hushåll",
    sortOrder: 10,
    keywords: [
      "tvättmedel",
      "tvätt",
      "sköljmedel",
      "diskmedel",
      "maskindiskmedel",
      "maskindisk",
      "handdiskmedel",
      "diskmaskin",
      "diskmaskinsmedel",
      "rengöring",
      "rengöringsmedel",
      "ytspray",
      "klorin",
      "allrengöring",
      "fönsterputs",
      "såpa",
      "golvtvätt",
      "toalettpapper",
      "toapapper",
      "hushållspapper",
      "pappershandduk",
      "servetter",
      "soppåse",
      "plastpåse",
      "aluminiumfolie",
      "gladpack",
      "bakplåtspapper",
      "plastfolie",
      "fryspåse",
      "matlåda",
      "matlådor",
      "hundmat",
      "hundfoder",
      "torrfoder",
      "blötfoder",
      "hundgodis",
      "kattmat",
      "kattgodis",
      "katt",
      "kattsand",
      "kattströ",
      "kattlåda",
      "grillkol",
      "kol",
      "tändvätska",
      "tändstickor",
      "stekspade",
      "stekpanna",
      "kastrull",
      "gryta",
      "kniv",
      "skärbräda",
    ],
  },
  {
    id: "baby",
    name: "Barn",
    sortOrder: 11,
    keywords: [
      "blöjor",
      "blöja",
      "blöjpaket",
      "pampers",
      "libero",
      "baby wipes",
      "våtservetter",
      "babyservett",
      "barnmat",
      "pure",
      "barnpure",
      "barnvälling",
      "välling",
      "barn gröt",
      "havregrynsgröt",
      "napp",
      "nappflaska",
      "flaska",
      "skötbädd",
      "skötväska",
      "skötvax",
      "babyolja",
      "babyschampoo",
      "babycreme",
      "balsam baby",
      "baby",
      "babyfilt",
      "barn",
    ],
  },
  {
    id: "other",
    name: "Övrigt",
    sortOrder: 12,
    keywords: [],
  },
];

export const departmentOrder = departments.map((d) => d.id);

export const getDepartment = (id: DepartmentId): Department =>
  departments.find((d) => d.id === id) ?? departments[departments.length - 1];
