name: build herrnan/laga
on:
  push:
    branches:
      - main

  pull_request:
  workflow_dispatch: # allow manually triggering builds

env:
  REGISTRY: ghcr.io

jobs:
  build-image:
    name: Build Custom Image
    permissions:
      contents: read
      packages: write
      id-token: write
    # Ubuntu 24.04 has Podman 4 installed from scratch
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - name: Generate Image Tags
        id: tags
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            TAGS="pr-${{ github.event.pull_request.number }} ${{ github.event.pull_request.head.sha }}"
          elif [ "${{ github.event_name }}" == "push" ] || [ "${{ github.ref_name }}" == "main" ]; then
            TAGS="latest ${{ github.sha }}"
          fi
          echo "tags=$TAGS" >> "$GITHUB_OUTPUT"

      - uses: jdx/mise-action@v4
      - run: "mise build"

      - name: Build Image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.repository }}
          containerfiles: Containerfile
          tags: ${{ steps.tags.outputs.tags }}

      - uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: github_workflow
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Images
        id: push
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.REGISTRY }}
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.tags.outputs.tags }}
